<?php
namespace WP_Parser_Validate;

use Psr\Log\LoggerAwareInterface;
use Psr\Log\LoggerAwareTrait;
use Psr\Log\NullLogger;

/**
 * Handles creating and updating posts from (functions|classes|files) generated by phpDoc.
 */
class Importer implements LoggerAwareInterface {

	use LoggerAwareTrait;

	/**
	 * Validate parsed data.
	 *
	 * Todo: skip @ignored functions.
	 * Todo: add sleep calls.
	 *
	 * @param array   $data       Parsed file(s) data.
	 * @param array   $assoc_args Optional arguments.
	 */
	public function validate( $data, $assoc_args = array() ) {

		$this->logger->info( 'Starting validation. This will take some time' );

		$exclude_notices = isset( $assoc_args['exclude-notices'] ) ? true : false;
		$time_start      = microtime( true );
		$file_number     = 1;
		$num_of_files    = count( $data );

		// Files from wp-content and third party libraries are excluded.
		// Get number of files (with excluded files subtracted).
		foreach ( $data as $file ) {
			if ( exclude_file( $file ) ) {
				$num_of_files--;
			}
		}

		$validator = new Validate;
		$validator->logger->set_format( 'wp-cli' );

		foreach ( $data as $file ) {
			if ( exclude_file( $file ) ) {
				continue;
			}

			$this->logger->info( sprintf( 'Processing file %1$s of %2$s "%3$s".', number_format_i18n( $file_number ), number_format_i18n( $num_of_files ), $file['path'] ) );
			$file_number ++;

			$validator->validate_file( $file );
			$this->display_logs( $validator->get_log_messages( $exclude_notices ) );
			$validator->flush_log();
			printf( "\n" );
		}

		$time_end = microtime( true );
		$time = $time_end - $time_start;

		$this->logger->info( 'Time: '.$time );
		if ( empty( $this->errors ) ) {
			$this->logger->notice( 'Validation complete!' );
		} else {
			$this->logger->info( 'Validation complete, but some errors were found:' );

			foreach ( $this->errors as $error ) {
				$this->logger->error( $error );
			}
		}
	}

	/**
	 * Display log messages.
	 *
	 * @param array   $logs       Logs to display.
	 * @access protected
	 */
	protected function display_logs( $logs ) {
		$out = '';

		if ( empty( $logs ) ) {
			return;
		}

		foreach ( $logs as $msg ) {
			$this->logger->info( $msg );
		}
	}
}
